model_name: sample_missing_data  # No model needed
model_description: Sample config to demonstrate missing data checks
data:
  project: STAGING_PROJECT
  source_type: kafka
  source_config:
    conn_id: kafka_staging
    topics:
      - wearable_heart_rate
tasks:
  - task_name: missing_data_checks
    type: data_checks
    enabled: true
    schedule: "0 8 * * *"
    checks:
      - type: "missing_data"
        name: "missing_data_check_1"
        topic: wearable_heart_rate
        window: "3 days"
        threshold: 1 # all the data missing in the window
    actions:
      - type: "send_notification"
        output_rule:
          - "missing_data_check_1.participants_id != []"
        config: []