model_name: sample_machine_learning_task  # No model needed
model_description: Sample config to demonstrate machine learning tasks
schedule: "0 8 * * *"
data:
  - name: wearable_heart_rate_kafka
    type: kafka
    config:
      conn_id: kafka_staging
      topics:
        - wearable_heart_rate
  - name: wearable_heart_rate_timescaledb
    type: timescaledb
    config:
      conn_id: timescale_staging
      tables:
        - wearable_heart_rate

tasks:
  - name: training_ml_model
    type: ml_training
    enabled: true
    path: github.com/radar-base/radar-ml
    branch: main
    config:
      script_path: /training/sample_project/train_model.py
      hyperparameters:
        learning_rate: 0.001
        dropout_rate: 0.5
        batch_size: 256
        num_epochs: 100
      server: "localhost:9000"
      mlflow_experiment_name: sample experiment
    depends_on:
      - data_processing

  - name: data_processing
    type: custom_task
    enabled: true
    path: /data_processing/sample_project/data_cleaning.py
    branch: main
    config:
      cleaning_level: "standard"
    depends_on:
      - wearable_heart_rate_kafka
      - wearable_heart_rate_timescaledb
