model_name: craving_prediction_model_v3
model_description: Sample config to demonstrate craving prediction model
schedule: "*/10 * * * *" # every 10 mins
intermediate_results_storage:
  type: SQL
  config:
    conn_id: timescale_staging
    database: intermediate_results_db
    table_prefix: craving_data

data:
  - name: mcraving_empatica_data
    type: kafka
    config:
      conn_id: kafka_staging
      project: STAGING_PROJECT
      lookback_window: 3600 # 1 hour
      format: avro
      topics:
        - s3-source-topic

tasks:
  - name: preprocessing_task
    type: custom
    enabled: true
    path: custom/mcraving_pipeline/preprocessing.py
    depends_on:
      - mcraving_empatica_data

  - name: craving_prediction_task
    type: custom
    enabled: true
    path: custom/mcraving_pipeline/prediction.py
    depends_on:
      - preprocessing_task

actions:
  - name: notify_participants
    type: "send_notification"
    filter_list_key: "craving_prediction_task"
    condition: 'craving_prediction_task.prediction == 1'
    depends_on:
      - craving_prediction_task
    time: "immediate"
    config:
      message: "Craving predicted for participant: {{ craving_prediction_task.user_id }}"
      backoff:
        enabled: true
        interval: 7200 # 2 hour
        backoff_key: "user_id"
        backoff_strategy: "fixed"
        max_messages: 3
        max_messages_units: "day"
