model_name: sample_anomaly_detection  # No model needed
model_description: Sample config to demonstrate heart rate spikes detection

intermediate_results_storage:
  type: sql
  config:
    conn_id: postgres_staging
    database:  intermediate_results_db
    table_prefix: sample_anomaly_detection

data:
  - name: wearable_heart_rate_kafka
    type: kafka
    config:
      conn_id: kafka_staging
      project: STAGING_PROJECT
      topics:
        - wearable_heart_rate
    depends_on:
      - anomaly_detection_sensor

tasks:
  - name: anomaly_detection
    type: custom
    enabled: true

    path: /sample_anomaly_detection/STAGING_PROJECT/spike_detection.py
    params:
      threshold: 200  # Heart rate threshold for spike detection
    depends_on:
      - wearable_heart_rate_kafka

actions:
  - name: notify_heart_rate_spike
    type: "send_notification"
    condition: "anomaly_detection.participants_id == true"
    config:
      time: "{{ timedelta(minutes=5) }}"
      message: "A heart rate spike has been detected for participant: {{ anomaly_detection.participants_id }}"
  - name: email_alert
    type: "email_alert"
    config:
      recipients:
        - "xyz@gmail.com"
      subject: "Heart Rate Spike Detected"
      body: "A heart rate spike has been detected for participant: {{ anomaly_detection.participants_id }}"
